services:
  - type: web
    name: ublf-php-app
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: starter
    envVars:
      - key: APACHE_DOCUMENT_ROOT
        value: /var/www/html/Lost&found/htdocs/public
    healthCheckPath: /
    autoDeploy: true

