services:
  - type: web
    name: ublf-php-app
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: starter
    envVars:
      - key: APACHE_DOCUMENT_ROOT
        value: /var/www/html/Lost&found/htdocs/public
      - key: PHP_INI_SCAN_DIR
        value: /usr/local/etc/php/conf.d
    healthCheckPath: /
    autoDeploy: true

